[package]
name = "zdtd"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simplelog = "0.12"
libc = "0.2"
sha2 = "0.10"
hex = "0.4"
